### ISSUE TITLE
I am getting ERROR in : Unexpected value 'Ng2TelInputModule in node_modules/ng2-tel-input/src/ng2-tel-input.module.d.ts  error when i update to 2.1.0 from 2.0.3.. previously worked very well.. let me know anybody have solution ?

### ISSUE THREAD

**Issue by sarikonda1** [gauravsoni119/ng2-tel-input#65]
ERROR in : Unexpected value 'Ng2TelInputModule in /var/lib/go-agent/pipelines/SMGT-APP-DEV/node_modules/ng2-tel-input/src/ng2-tel-input.module.d.ts' imported by the module 'SharedManagementModule in /var/lib/go-agent/pipelines/SMGT-APP-DEV/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.
node_modules/ng2-tel-input/src/ng2-tel-input.d.ts(18,21): error TS2694: Namespace '"/var/lib/go-agent/pipelines/SMGT-APP-DEV/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
node_modules/ng2-tel-input/src/ng2-tel-input.d.ts(19,21): error TS2694: Namespace '"/var/lib/go-agent/pipelines/SMGT-APP-DEV/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDefWithMeta'.
node_modules/ng2-tel-input/src/ng2-tel-input.module.d.ts(6,21): error TS2694: Namespace '"/var/lib/go-agent/pipelines/SMGT-APP-DEV/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDefWithMeta'.
node_modules/ng2-tel-input/src/ng2-tel-input.module.d.ts(7,21): error TS2694: Namespace '"/var/lib/go-agent/pipelines/SMGT-APP-DEV/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDef'

**Comment by gauravsoni119** [comment]
Which version of Angular you are using? Make sure that you have the latest version(Angular 9).

**Comment by sarikonda1** [comment]
> Which version of Angular you are using? Make sure that you have the latest version(Angular 9).

Does this version of plugin supports only angular 9 ?

**Comment by viniciuspsw** [comment]
I'm facing same error using Angular 9. Has someone found a solution?

**Comment by gauravsoni119** [comment]
![Screenshot from 2020-02-29 12-05-39](https://user-images.githubusercontent.com/8476712/75606350-02901480-5aec-11ea-8ed0-2bbbc7c2fd45.png)


From this table, it looks like the shipping library with angular 9 is not compatible with the older angular apps. So, I will publish the new version which will revert the changes of new version.

Thanks for the issue.

**Comment by gauravsoni119** [comment]
New version **2.2.0** compiled with angular 8.

**Comment by devprotim** [comment]
'Ng2TelInputModule' does not appear to be an NgModule class. Im using angular 13.
